### ISSUE TITLE
Add markdown rule MD047 to resulting .md files (Files should end with a single newline character)

### ISSUE THREAD

**Issue by baardhermansen** [joachimdalen/bicepdocs#41]
### What formatter are you using?

Markdown

### Bicep version

v0.23.1

### Bicepdocs version

0.1.2

### What operating system are you using?

Windows

### What is the bug you want to report?

Missing a single newline character at the end of the .md files, so they follow markdownlint rules, specifically [MD047](https://github.com/DavidAnson/markdownlint/blob/v0.31.1/doc/md047.md).

**Comment by joachimdalen** [comment]
Hi! 

I'll see if I can get it done during the week, as well as some other updates. I plan to pickup development on this one again.

**Comment by joachimdalen** [comment]
This should be fixed in `v0.1.3`
